spring.application.name=api-core
server.port=8080
spring.config.import=optional:file:.env[.properties]


# Configurações de conexão com o PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Outras configurações 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.open-in-view=false

# AWS Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}